### ISSUE TITLE
یاد گرفتن فیلترینک 

### ISSUE THREAD

**Issue by amirhoosin54** [cood-filter-rubika/filter-rubika#53]
یاد گرفتن فیلترینک و نظام دادن به روبیکا

**Comment by amirhoosin54** [comment]
یاد گرفتن فیلترینک

**Comment by amirhoosin54** [comment]
برنامه خوبیه بر نظرم ولی من تازه میخوام برم داخلش

**Comment by amirhoosin54** [comment]
**می‌خوام یاد بگیرم**

**Comment by amirhoosin54** [comment]
![Uploading Screenshot_2024-12-28-11-05-19-249_ir.medu.shad.jpg…]()

**Comment by Nezir42** [comment]
عاجی. من هیچی. بلد نیسم. کسی. هس کمکم کنه
